gorengan = ('Bakwan', 'Cireng', 'Tahu')
sop = ('Sop Iga', 'Sop Buntut', 'Sop Kaki')
nasi = ('Nasi Uduk', 'Nasi Goreng', 'Nasi Remes')
# nested tuple
makanan = (gorengan, sop, nasi)
print('--------Makanan Sop---------')
print(makanan[0])
print('--------Cetak peritem---------')
print(makanan[0][0])
print(makanan[1][1])
print(makanan[2][2])
print('--------Cetak Semua item---------')
print(makanan)
